# Main IcyIRC config

[general]
	name             = 'IcyIRC'
	version          = '0.1'

[irc]
	default_quit_msg = 'IcyIRC WebIRC Client version 0.1'
	default_kick_msg = ''
	default_chan     = '#parasprite'
	default_serv     = ''

	[webirc]
		password     = ''

[server]
	host             = 'localhost'
	port             = 8002